app/urls.py
from django.urls import path
from app.views import *

urlpatterns = [
    path('',index,name='index'),


    path('U/<slug:category_slug>/',product_list,name='product_list_by_category'),
    # Host city urls
    path('en/bordeaux',bordeaux_page,name='bordeaux'),
    path('en/lille_metropole',lille_metropole_page,name='lille_metropole'),
    path('en/lyon',lyon_page,name='lyon'),
    path('en/marseille',marseille_page,name='marseille'),
    path('en/nantes',nantes_page,name='nantes'),
    path('en/nice',nice_page,name='nice'),
    path('en/saint_denis',saint_denis_page,name='saint_denis'),
    path('en/saint_etienne',saint_etienne_page,name='saint_etienne'),
    path('en/toulouse',toulouse_page,name='toulouse'),

    # Qualified team page
    path('en/argentina',argentina_page,name='argentina'),  
    path('en/australia',australia_page,name='australia'),  
    path('en/chile',chile_page,name='chile'),  
    path('en/england',england_page,name='england'),  
    path('en/fiji',fiji_page,name='fiji'),  
    path('en/teamfrance',teamfrance_page,name='teamfrance'),  
    path('en/georgia',georgia_page,name='georgia'),  
    path('en/ireland',ireland_page,name='ireland'),  
    path('en/Italy',Italy_page,name='Italy'),  
    path('en/japan',japan_page,name='japan'),  
    path('en/namibia',namibia_page,name='namibia'),  
    path('en/new_zealand',new_zealand_page,name='new_zealand'),  
    path('en/portugal',portugal_page,name='portugal'),  
    path('en/romania',romania_page,name='romania'),  
    path('en/samoa',samoa_page,name='samoa'),  
    path('en/south_africa',south_africa_page,name='south_africa'),  
    path('en/scotland',scotland_page,name='scotland'),  
    path('en/tonga',tonga_page,name='tonga'),  
    path('en/uruguay',tonga_page,name='uruguay'),  
    path('en/wales',wales_page,name='wales'),  


    # others
    path('en/contact',contact_page,name='wales'),  
    path('en/parking_booking',parking_booking_page,name='parking_book'),  
    path('en/accessibility_booking',accessibility_booking_page,name='accessibility_booking'),  
    path('en/faq',faq_page,name='faq'),  



] 

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

rugby/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("account.urls")),
    path('',include("app.urls")),
    path('shop/', include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('', include('chat.urls')),

]

account/models/UserModel.py
# from django.db import models
# from .AbstractModel import BaseUser

# class User(BaseUser):
#     username = models.CharField(max_length=150, unique=False)
#     first_name = models.CharField(max_length=50, null=True)
#     last_name = models.CharField(max_length=50, null=True)
#     date_birth = models.DateField(null=True)
#     mobile_phone = models.CharField(max_length=14, null=True)
#     street_address = models.CharField(max_length=50, null=True)
#     postal_code = models.CharField(max_length=45, null=True)
#     city = models.CharField(max_length=60, null=True)
#     country = models.CharField(max_length=60, null=True)
#     Favourite_national_team = models.CharField(max_length=50, null=True)
#     Favourite_city = models.CharField(max_length=60, null=True)
#     favourite_language = models.CharField(max_length=60, null=True)
#     club_coeur = models.CharField(max_length=60, null=True)
#     sexe_user = models.CharField(max_length=50, null=True)
#     password_user = models.CharField(max_length=90, null=True)
#     card_number = models.CharField(max_length=35, null=True)
#     exp_date = models.CharField(max_length=35, null=True)
#     CVV = models.CharField(max_length=4, null=True)
#     account_name = models.CharField(max_length=53, null=True)
#     owner_name = models.CharField(max_length=50, null=True)
#     IBAN_accountNumber = models.CharField(max_length=50, null=True)
#     BIC_SWIFT = models.CharField(max_length=60, null=True)
#     address_gmail = models.CharField(max_length=95, null=True)
#     password_gmail = models.CharField(max_length=95, null=True)

#     USERNAME_FIELD = 'email'


#     def __str__(self):
#             return self.first_name
    
#     class Meta:
#         db_table = 'user' 


# from django.db import models
# from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
# from django.utils import timezone
# import uuid

# class BaseUser(AbstractBaseUser, PermissionsMixin):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     username = models.CharField(max_length=150, unique=False ,default=None)
#     email = models.EmailField(unique=True)
#     USERNAME_FIELD = 'email'
#     EMAIL_FIELD = 'email'
#     REQUIRED_FIELDS = ['username']

# class User(BaseUser):
#     # Fields from User model
#     first_name = models.CharField(max_length=50, null=True)
#     last_name = models.CharField(max_length=50, null=True)
#     date_birth = models.DateField(null=True)
#     mobile_phone = models.CharField(max_length=14, null=True)
#     street_address = models.CharField(max_length=50, null=True)
#     postal_code = models.CharField(max_length=45, null=True)
#     city = models.CharField(max_length=60, null=True)
#     country = models.CharField(max_length=60, null=True)
#     Favourite_national_team = models.CharField(max_length=50, null=True)
#     Favourite_city = models.CharField(max_length=60, null=True)
#     favourite_language = models.CharField(max_length=60, null=True)
#     club_coeur = models.CharField(max_length=60, null=True)
#     sexe_user = models.CharField(max_length=50, null=True)
#     password_user = models.CharField(max_length=90, null=True)
#     card_number = models.CharField(max_length=35, null=True)
#     exp_date = models.CharField(max_length=35, null=True)
#     CVV = models.CharField(max_length=4, null=True)
#     account_name = models.CharField(max_length=53, null=True)
#     owner_name = models.CharField(max_length=50, null=True)
#     IBAN_accountNumber = models.CharField(max_length=50, null=True)
#     BIC_SWIFT = models.CharField(max_length=60, null=True)
#     address_gmail = models.CharField(max_length=95, null=True)
#     password_gmail = models.CharField(max_length=95, null=True)
    
#     # Fields from CustomUser model
#     AGENT = 'agent'
#     CLIENT = 'client'
#     MANAGER = 'manager'
#     ROLES_CHOICES = (
#         (AGENT, 'Agent'),
#         (MANAGER, 'Manager'),
#     )
#     name = models.CharField(max_length=255, blank=True, default='')
#     role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=CLIENT)
   
#     date_joined = models.DateTimeField(default=timezone.now)
#     # last_login = models.DateTimeField(blank=True, null=True)
    
#     objects = UserManager()

# import uuid
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser,PermissionsMixin
from django.utils import timezone

class UserAccount(BaseUserManager):
    def create_user(self, email,password=None, **kwargs):
       
        if not email:
            raise ValueError("Users must have an email address")

        email = self.normalize_email(email)
        email = email.lower()

        user = self.model(
            email=email ,
            **kwargs
           )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None ,**kwargs):
       
        user = self.create_user(
            email,
            password=password,
           **kwargs
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)



class User(AbstractBaseUser,PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'
    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=MANAGER)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(
        max_length=255,
        unique=True
        ,default=None
    )

    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     username = models.CharField(max_length=150, unique=False ,default=None)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_birth = models.DateField(null=True)
    mobile_phone = models.CharField(max_length=14, null=True)
    street_address = models.CharField(max_length=50, null=True)
    postal_code = models.CharField(max_length=45, null=True)
    city = models.CharField(max_length=60, null=True)
    country = models.CharField(max_length=60, null=True)
    Favourite_national_team = models.CharField(max_length=50, null=True)
    Favourite_city = models.CharField(max_length=60, null=True)
    favourite_language = models.CharField(max_length=60, null=True)
    club_coeur = models.CharField(max_length=60, null=True)
    sexe_user = models.CharField(max_length=50, null=True)
    password_user = models.CharField(max_length=90, null=True)
    card_number = models.CharField(max_length=35, null=True)
    exp_date = models.CharField(max_length=35, null=True)
    CVV = models.CharField(max_length=4, null=True)
    account_name = models.CharField(max_length=53, null=True)
    owner_name = models.CharField(max_length=50, null=True)
    IBAN_accountNumber = models.CharField(max_length=50, null=True)
    BIC_SWIFT = models.CharField(max_length=60, null=True)
    address_gmail = models.CharField(max_length=95, null=True)
    password_gmail = models.CharField(max_length=95, null=True)

    # date_joined = models.DateTimeField(default=timezone.now)
    # last_login = models.DateTimeField(blank=True, null=True)

    

    objects = UserAccount()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name",'last_name']

    def __str__(self):
        return self.email

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from account.forms import AddUserForm, EditUserForm
from account.models import User
from .models import Room
from django.views.decorators.csrf import csrf_exempt


# @require_POST
@csrf_exempt
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
                
        messages.success(request, 'The room was deleted!')

        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have access to delete rooms!')

        return redirect('/chat-admin/')


@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()

    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms
    })


@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)

        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                form.save()
                
                messages.success(request, 'The changes was saved!')

                return redirect('/chat-admin/')
        else:
            form = EditUserForm(instance=user)

        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to edit users!')

        return redirect('/chat-admin/')


@login_required
def add_user(request):
    # if request.user.has_perm('user.add_user'):
    if request.method == 'POST':
        form = AddUserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_staff = True
            user.set_password(request.POST.get('password'))
            user.save()

            if user.role == User.MANAGER: 
                group = Group.objects.get(name='Managers')
                group.user_set.add(user)
            
            messages.success(request, 'The user was added!')

            return redirect('/chat-admin/')
    else:
        form = AddUserForm()

    return render(request, 'chat/add_user.html', {
        'form': form
    })
    

chat/templates/chat/add_user.html
{% extends 'chat/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Add user</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add user</button>
    </form>
{% endblock %}

chat/templates/chat/admin.html
{% extends 'chat/base.html' %}

{% block content %}
    <h1 class="text-2xl">Chat admin</h1>

    {% if perms.user.add_user %}
        <div class="mt-8">
            <h2 class="mb-4 text-lg">Users</h2>

            <a href="{% url 'chat:add_user' %}" class="inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Add user</a>

            <div class="mt-6">
                {% for user in users %}
                    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">
                       

                        <p class="px-2">{{ user.email }}</p>

                        <p class="px-2">{{ user.get_role_display }}</p>

                        <p class="px-2 text-right">
                          
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>

        {% include 'chat/partials/room_list.html' %}
    </div>
{% endblock %}

chat/templates/chat/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl">

                <div class="flex items-center space-x-4">
                    <a >Home</a>
                    <a >About</a>
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

chat/templates/chat/edit_user.html
{% extends 'chat/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">Edit user</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-6 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Save changes</button>
    </form>
{% endblock %}

chat/templates/chat/room.html
{% extends 'chat/base.html' %}

{% load static chatextras %}

{% block content %}
    <h1 class="text-2xl">Room "{{ room.uuid }}"</h1>

    <hr class="my-6">

    <p class="mb-6">
        <b>Name: </b>{{ room.client }}<br>
        <b>Started: </b>{{ room.created_at|timesince }} ago<br>
        <b>Status: </b>{{ room.get_status_display }}<br>
        <b>Page: </b>{{ room.url }}<br>
        <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
    </p>

    <hr class="mb-6">

    <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
        {% for message in room.messages.all %}
            <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
                {% if not message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}

                <div>
                    <div class="p-4 rounded-xl {% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>

                    <span class="text-xs text-gray-500 leading-none">{{ message.created_at|timesince }} ago</span>
                </div>

                {% if message.created_by %}
                    <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 text-center pt-2">
                        {{ message.sent_by|initials }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    {% if room.status == 'active' %}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    {% endif %}
{% endblock %}

{% block scripts %}
    {% if room.status == 'active' %}
        {{ room.uuid|json_script:'room_uuid' }}
        {{ request.user.name|json_script:'user_name' }}
        {{ request.user.id|json_script:'user_id' }}

        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}

chat/templates/chat/user_detail.html
{% extends 'chat/base.html' %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{ user.name }}</h1>

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-4 text-lg">Rooms</h2>

        {% include 'chat/partials/room_list.html' %}
    </div>
{% endblock %}